#-------------------------------------------------------------------------------
download_exim()
#-------------------------------------------------------------------------------
{
  info "Downloading source code"

  set -x
      git clone \
          "rose-dev@rosecompiler1.llnl.gov:rose/c/${application}.git" \
          "${application}-src" \
          || exit 1
      cd "${application}-src/" || exit 1
  set +x
}

#-------------------------------------------------------------------------------
patch_exim__rose()
#-------------------------------------------------------------------------------
{
  info "ROSE patching not required"
}

#-------------------------------------------------------------------------------
configure_exim__generic()
#-------------------------------------------------------------------------------
{
  [ -z "$CC" ] && fail "Required C compiler variable not set: \$CC"

  cp src/EDITME Local/Makefile
  (
      echo "CC=$CC"
      echo "CFLAGS=-I$(pwd)/build-Linux-x86_64"
      echo "EXIM_USER=$USER"
      echo "BIN_DIRECTORY=$(pwd)/install_tree/bin"
      echo "CONFIGURE_FILE=$(pwd)/install_tree/configure"
  ) 2>&1 >> Local/Makefile
  [ ${PIPESTATUS[0]} -ne 0 ] && exit 1 || true

  # Create eximon configuration
  cp exim_monitor/EDITME Local/eximon.conf

  cat src/pcre/config.h | sed 's/#include "..\/os.h"/#include "os.h"/g' > src/pcre/config.h-new
  cp src/pcre/config.h src/pcre/config.h-old
  cp src/pcre/config.h-new src/pcre/config.h

  #-----------------------------------------------------------------------------
  # Hack
  #-----------------------------------------------------------------------------
  # Hack: Replace #include "cnumber.h" with the actual number contained in
  # that header file:
  #
  # // DQ (10/23/2012): Modified source code to avoid this classic source-to-source
  # // issue (represented by ROSE test code test2012_78.c).
  files="$(grep -rn "#include \"cnumber.h\"" * | awk '{print $1}' | sed 's/:.*:.*//g')"
  # Generated by Make
  #cnumber_file="$(find . -iname "*cnumber\.h")"
  #cnumber="$(cat "$cnumber_file")"
  cnumber="6"
  for f in $files; do
    echo "Hacking file '$f' to replace '#include \"cnumber.h\"' with the actual contents '${cnumber}'..."
    mv $f $f-old
    cat "${f}-old" | sed 's/#include "cnumber\.h"/'${cnumber}'/g' > "$f"
  done
}

#-------------------------------------------------------------------------------
configure_exim__rose()
#-------------------------------------------------------------------------------
{
  info "Configuring application for ROSE compiler='${rose_compiler}'"

  set -x
      CC="${rose_compiler}" \
          configure_exim__generic || exit 1
  set +x
}

#-------------------------------------------------------------------------------
configure_exim__gcc()
#-------------------------------------------------------------------------------
{
  info "Configuring application for default compiler='gcc'"

  set -x
      CC="gcc" \
          configure_exim__generic || exit 1
  set +x
}

#-------------------------------------------------------------------------------
compile_exim()
#-------------------------------------------------------------------------------
{
  info "Compiling application"

  set -x
      make -j${parallelism}  || exit 1
  set +x
}
