compile_postfix()
{
  local translator="$1" parallelism="${parallelism:=1}"

  #-----------------------------------------------------------------------------
  # Configure  Meta Information
  #-----------------------------------------------------------------------------
  declare -r VERSION=2.9.4
  declare -r TARBALL="postfix-${VERSION}.tar.gz"
  declare -r DOWNLOAD_URL="http://cdn.postfix.johnriley.me/mirrors/postfix-release/official/${TARBALL}"

  #-----------------------------------------------------------------------------
  # Create Workspace
  #-----------------------------------------------------------------------------
  create_workspace "postfix"
  cd "postfix" || exit 1

  #-----------------------------------------------------------------------------
  # Download and Unpack
  #-----------------------------------------------------------------------------
  download "$TARBALL" "$DOWNLOAD_URL"
  tar xvf "${TARBALL}" || exit 1
  cd "postfix-${VERSION}" || exit 1

  #-----------------------------------------------------------------------------
  # Hack
  #-----------------------------------------------------------------------------
  # Patch generated by:
  #
  #   diff -U 10 \
  #       ./src/global/memcache_proto.c \
  #       memcache_proto_modified_for_rose.c \
  #   > patch-memcache_proto.c
  #
  curl --insecure \
    https://raw.github.com/gist/3981468/62f9ccb80f2514b3aec7e6a2416564b5fa2ef625/patch-memcache_proto.c | \
    patch -p1 -i -

  #-----------------------------------------------------------------------------
  # Build
  #-----------------------------------------------------------------------------
  make makefiles CC="$translator" || exit 1

  make --keep-going -j${parallelism} || exit 1
  make install -j${parallelism} || exit 1
}
