#-------------------------------------------------------------------------------
download_sudo()
#-------------------------------------------------------------------------------
{
  info "Downloading source code"

  set -x
      git clone \
          "rose-dev@rosecompiler1.llnl.gov:rose/c/${application}.git" \
          "${application}-src" \
          || exit 1
      cd "${application}-src/" || exit 1
  set +x
}

#-------------------------------------------------------------------------------
patch_sudo__rose()
#-------------------------------------------------------------------------------
{
  info "ROSE patching not required"

  #-----------------------------------------------------------------------------
  # Hack
  #-----------------------------------------------------------------------------
  # Patch generated by:
  #
  #   diff -U 10 \
  #       ./plugins/sudoers/sudoreplay.c \
  #       sudoreplay-modified_for_rose.c \
  #   > patch-sudoreplay.c
  #
#  curl --insecure \
#    https://raw.github.com/gist/4026218/f9d4a12d2c9ff7db327026acd4e715c7a133bcc4/patch-sudoreplay.c | \
#    patch -p1 -i -
  cat patches/patch-sudoreplay.c | patch -p1 -i - || exit 1
  if [ ${PIPESTATUS[0]} -ne 0 ]; then
    echo "[FATAL] Failed to patch sudoreplay.c"
    exit 1
  fi
}

#-------------------------------------------------------------------------------
configure_sudo__rose()
#-------------------------------------------------------------------------------
{
  info "Configuring application for ROSE compiler='${CC}'"

  set -x
      CC="${CC} -rose:C89_only" \
          ./configure --prefix="$(pwd)/install_tree" || exit 1
  set +x
}

#-------------------------------------------------------------------------------
configure_sudo__gcc()
#-------------------------------------------------------------------------------
{
  info "Configuring application for default compiler='gcc'"

  set -x
      CC="gcc" \
          ./configure --prefix="$(pwd)/install_tree" || exit 1
  set +x
}

#-------------------------------------------------------------------------------
compile_sudo()
#-------------------------------------------------------------------------------
{
  info "Compiling application"

  set -x
      make -j${parallelism}  || exit 1
  set +x
}
