compile_sudo()
{
  local translator="$1" parallelism="${parallelism:=1}"

  #-----------------------------------------------------------------------------
  # Configure  Meta Information
  #-----------------------------------------------------------------------------
  declare -r VERSION=1.8.6
  declare -r TARBALL="sudo-${VERSION}.tar.gz"
  declare -r DOWNLOAD_URL="ftp://ftp.sudo.ws/pub/sudo/${TARBALL}"

  #-----------------------------------------------------------------------------
  # Create Workspace
  #-----------------------------------------------------------------------------
  create_workspace "sudo"
  cd "sudo" || exit 1

  #-----------------------------------------------------------------------------
  # Download and Unpack
  #-----------------------------------------------------------------------------
  download "$TARBALL" "$DOWNLOAD_URL"
  tar xvf "${TARBALL}" || exit 1
  cd "sudo-${VERSION}" || exit 1

  #-----------------------------------------------------------------------------
  # Hack
  #-----------------------------------------------------------------------------
  # Patch generated by:
  #
  #   diff -U 10 \
  #       ./plugins/sudoers/sudoreplay.c \
  #       sudoreplay-modified_for_rose.c \
  #   > patch-sudoreplay.c
  #
  curl --insecure \
    https://raw.github.com/gist/4026218/f9d4a12d2c9ff7db327026acd4e715c7a133bcc4/patch-sudoreplay.c | \
    patch -p1 -i -

  #-----------------------------------------------------------------------------
  # Build
  #-----------------------------------------------------------------------------
  CC="$translator" ./configure --prefix="$(pwd)/install_tree" || exit 1

  make --keep-going -j${parallelism} || exit 1
  #make install -j${parallelism} || exit 1
}
