#-------------------------------------------------------------------------------
download_zsh()
#-------------------------------------------------------------------------------
{
  info "Downloading source code"

  set -x
      git clone \
          "rose-dev@rosecompiler1.llnl.gov:rose/c/${application}.git" \
          "${application}-src" \
          || exit 1
      cd "${application}-src/" || exit 1
  set +x
}

#-------------------------------------------------------------------------------
install_deps_zsh()
#-------------------------------------------------------------------------------
{
  info "[Dependencies] No external dependencies need to be installed"
}

#-------------------------------------------------------------------------------
patch_zsh()
#-------------------------------------------------------------------------------
{
  info "Patching application"

  #-----------------------------------------------------------------------------
  # src/gnutls.c
  #-----------------------------------------------------------------------------
  info "[Patch] Applying patch for zle_bindings.c"
  # Patch generated by:
  #
  #   diff -U 10 \
  #       ./Src/Zle/zle_bindings.c \
  #       zle_bindings-modified_for_rose.c \
  #   > patch-zle_bindings.c
  #
  #curl --insecure \
  #  https://raw.github.com/gist/4020001/6505ec18af01163789bc8d038890a5f3d8b0267e/patch-zle_bindings.c | \
  #  patch -p1 -i -
  cat patches/patch-zle_bindings.c  | patch -p1 -i - || exit 1
  if [ ${PIPESTATUS[0]} -ne 0 ]; then
    echo "[FATAL] Failed to patch zle_bindings.c"
    exit 1
  fi
}

#-------------------------------------------------------------------------------
configure_zsh__rose()
#-------------------------------------------------------------------------------
{
  info "Configuring application for ROSE compiler='${CC}'"

  set -x
      #./Util/preconfig # Generate configure script (Requires Autoconf 2.59+)
      # Use "--without-tcsetpgrp", otherwise error "no controlling TTY" when run in Jenkins
      CC="${CC} -rose:C89_only" \
          ./configure \
              --without-tcsetpgrp \
              --prefix="$(pwd)/install_tree" || exit 1
  set +x
}

#-------------------------------------------------------------------------------
configure_zsh__gcc()
#-------------------------------------------------------------------------------
{
  info "Configuring application for default compiler='gcc'"

  set -x
      # Use "--without-tcsetpgrp", otherwise error "no controlling TTY" when run in Jenkins
      CC="gcc" \
          ./configure \
              --without-tcsetpgrp \
              --prefix="$(pwd)/install_tree" || exit 1
  set +x
}

#-------------------------------------------------------------------------------
compile_zsh()
#-------------------------------------------------------------------------------
{
  info "Compiling application"

  set -x
      make -j${parallelism}  || exit 1
  set +x
}
