compile_zsh()
{
  local translator="$1" parallelism="${parallelism:=1}"

  #-----------------------------------------------------------------------------
  # Configure  Meta Information
  #-----------------------------------------------------------------------------
  declare -r VERSION=5.0.0
  declare -r TARBALL="zsh-${VERSION}.tar.gz"
  declare -r DOWNLOAD_URL="ftp://ftp.zsh.org/pub/${TARBALL}"

  #-----------------------------------------------------------------------------
  # Create Workspace
  #-----------------------------------------------------------------------------
  create_workspace "zsh"
  cd "zsh" || exit 1

  #-----------------------------------------------------------------------------
  # Download and Unpack
  #-----------------------------------------------------------------------------
  download "$TARBALL" "$DOWNLOAD_URL"
  tar xvf "${TARBALL}" || exit 1
  cd "zsh-${VERSION}" || exit 1

  #-----------------------------------------------------------------------------
  # Hack
  #-----------------------------------------------------------------------------
  # Patch generated by:
  #
  #   diff -U 10 \
  #       ./Src/Zle/zle_bindings.c \
  #       zle_bindings-modified_for_rose.c \
  #   > patch-zle_bindings.c
  #
  curl --insecure \
    https://raw.github.com/gist/4020001/6505ec18af01163789bc8d038890a5f3d8b0267e/patch-zle_bindings.c | \
    patch -p1 -i -

  #-----------------------------------------------------------------------------
  # Build
  #-----------------------------------------------------------------------------
  # Use "--without-tcsetpgrp", otherwise error "no controlling TTY" when run in Jenkins
  CC="$translator" ./configure \
      --prefix="$(pwd)/install_tree" \
      --without-tcsetpgrp \
  || exit 1

  make --keep-going -j${parallelism} || exit 1
  make install -j${parallelism} || exit 1
}
